version: '3'

services:
  web:
    build:
      context: ./docker/web/nginx
      dockerfile: ./Dockerfile.m1
    ports:
      - 8030:80
    volumes:
#      ローカル環境での開発用設定ファイル
      - ./docker/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      本番環境でHTTPS化する際の設定ファイル
#      - ./docker/web/nginx/conf.d/ssl.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/nginx/volumes/log:/var/log/nginx
      - ./src/public:/var/www/html/public:cached
    links:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/app/php-fpm/Dockerfile.m1
    volumes:
      - ./src:/var/www/html:cached
    links:
      - db
  db:
    build:
      context: ./docker/db/mysql
      dockerfile: ./Dockerfile.m1
    volumes:
      - ./docker/db/mysql/volumes/data:/var/lib/mysql
      - ./docker/db/mysql/volumes/log:/var/log
    ports:
      - 33060:3306




